version: '3.8'
services:
  fireside-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fireside-blog
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    # Uncomment if you need to install additional dependencies at runtime
    # command: ["npm", "run", "start"]
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
