version: '3.8'
services:
  fireside-blog:
    image: atemndobs/fireside-blog-amd64:v0.3
    container_name: fireside-blog
    restart: unless-stopped
    ports:
      - "8087:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    # Healthcheck to ensure the application is running properly
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
